export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE' ,
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
}

export const registerConstant = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
}