export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE' ,
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
}

export const registerConstant = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
}

export const categoryConstant = {
    GET_CATEGORY_REQUEST: 'GET_CATEGORY_REQUEST',
    GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    POST_CATEGORY_REQUEST: 'POST_CATEGORY_REQUEST',
    POST_CATEGORY_FAILURE: 'POST_CATEGORY_FAILURE',
    POST_CATEGORY_SUCCESS: 'POST_CATEGORY_SUCCESS',
}

export const productConstant = {
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    POST_PRODUCT_REQUEST: 'POST_PRODUCT_REQUEST',
    POST_PRODUCT_FAILURE: 'POST_PRODUCT_FAILURE',
    POST_PRODUCT_SUCCESS: 'POST_PRODUCT_SUCCESS',
}

export const initialDataConstant = {
    GET_INITIAL_DATA_REQUEST: 'GET_INITIAL_DATA_REQUEST',
    GET_INITIAL_DATA_SUCCESS: 'GET_INITIAL_DATA_SUCCESS',
    GET_INITIAL_DATA_FAILURE: 'GET_INITIAL_DATA_FAILURE',
}